export const AUTH_ROUTE_PATH = '/auth'
export const DOCTOR_PATH = '/doctors'
export const REGISTER_PATH = '/reg'
export const APPOINTMENT_PATH = '/appointment/:doctorId'
export const TIMESLOTS_MANAGEMENT = '/times/:doctorId'